CREATE DATABASE IF NOT EXISTS pa_user CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS pa_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS pp_user CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;